services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: orderflow
      POSTGRES_USER: orderflow
      POSTGRES_PASSWORD: orderflow
    ports:
      - "5432:5432"
    volumes:
      - orderflow_pg:/var/lib/postgresql/data

  order-service:
    build:
      context: ./services/order-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/orderflow
      SPRING_DATASOURCE_USERNAME: orderflow
      SPRING_DATASOURCE_PASSWORD: orderflow
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  orderflow_pg: