server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: order-service
    version: ${APP_VERSION:0.6.0}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/orderdb}
    username: ${SPRING_DATASOURCE_USERNAME:order}
    password: ${SPRING_DATASOURCE_PASSWORD:order}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  health:
    rabbit:
      enabled: false

orderflow:
  messaging:
    exchange: orderflow.order.events
    orderCreatedRoutingKey: order.created
    orderCreatedQueue: orderflow.order.created